In [1]:

import pandas as pd

df = pd.read_csv(r"C:\Users\user\Documents\Machine learning\machine-learning-ex1\ex1\ex1data2.txt",names = ['House Size(Square feet)',"#Bedrooms",'Price'])
df

House Size(Square feet)  #Bedrooms   Price
0                      2104          3  399900
1                      1600          3  329900
2                      2400          3  369000
3                      1416          2  232000
4                      3000          4  539900
5                      1985          4  299900
6                      1534          3  314900
7                      1427          3  198999
8                      1380          3  212000
9                      1494          3  242500
10                     1940          4  239999
11                     2000          3  347000
12                     1890          3  329999
13                     4478          5  699900
14                     1268          3  259900
15                     2300          4  449900
16                     1320          2  299900
17                     1236          3  199900
18                     2609          4  499998
19                     3031          4  599000
20                     1767          3  252900
21                     1888          2  255000
22                     1604          3  242900
23                     1962          4  259900
24                     3890          3  573900
25                     1100          3  249900
26                     1458          3  464500
27                     2526          3  469000
28                     2200          3  475000
29                     2637          3  299900
30                     1839          2  349900
31                     1000          1  169900
32                     2040          4  314900
33                     3137          3  579900
34                     1811          4  285900
35                     1437          3  249900
36                     1239          3  229900
37                     2132          4  345000
38                     4215          4  549000
39                     2162          4  287000
40                     1664          2  368500
41                     2238          3  329900
42                     2567          4  314000
43                     1200          3  299000
44                      852          2  179900
45                     1852          4  299900
46                     1203          3  239500

In [2]:
x1 = df['House Size(Square feet)']
x2 = df['#Bedrooms']
y = df['Price']


print(x1)
print(x2)
print(y)

import numpy as np
lst = [1 for i in range(len(x1))]

#creating the matrix X by adding column of ones
X = np.array([lst,x1,x2])
X = X.transpose()    ####this transpose is used for making the matrix 
print(X)

Y = np.array(y)
Y = Y.transpose()
Y = Y.reshape(len(y),1)
print(Y)


0     2104
1     1600
2     2400
3     1416
4     3000
5     1985
6     1534
7     1427
8     1380
9     1494
10    1940
11    2000
12    1890
13    4478
14    1268
15    2300
16    1320
17    1236
18    2609
19    3031
20    1767
21    1888
22    1604
23    1962
24    3890
25    1100
26    1458
27    2526
28    2200
29    2637
30    1839
31    1000
32    2040
33    3137
34    1811
35    1437
36    1239
37    2132
38    4215
39    2162
40    1664
41    2238
42    2567
43    1200
44     852
45    1852
46    1203
Name: House Size(Square feet), dtype: int64
0     3
1     3
2     3
3     2
4     4
5     4
6     3
7     3
8     3
9     3
10    4
11    3
12    3
13    5
14    3
15    4
16    2
17    3
18    4
19    4
20    3
21    2
22    3
23    4
24    3
25    3
26    3
27    3
28    3
29    3
30    2
31    1
32    4
33    3
34    4
35    3
36    3
37    4
38    4
39    4
40    2
41    3
42    4
43    3
44    2
45    4
46    3
Name: #Bedrooms, dtype: int64
0     399900
1     329900
2     3

In [3]:
XT=X.transpose()

print(XT)
print (X)

a=XT.dot(X)
print(a)
inverse_a = np.linalg.inv(a)   ##inverse of XT*X
print(inverse_a)

b=XT.dot(Y)
print (b)

c=inverse_a.dot(b)
theta=c
theta

[[   1    1    1    1    1    1    1    1    1    1    1    1    1    1
     1    1    1    1    1    1    1    1    1    1    1    1    1    1
     1    1    1    1    1    1    1    1    1    1    1    1    1    1
     1    1    1    1    1]
 [2104 1600 2400 1416 3000 1985 1534 1427 1380 1494 1940 2000 1890 4478
  1268 2300 1320 1236 2609 3031 1767 1888 1604 1962 3890 1100 1458 2526
  2200 2637 1839 1000 2040 3137 1811 1437 1239 2132 4215 2162 1664 2238
  2567 1200  852 1852 1203]
 [   3    3    3    2    4    4    3    3    3    3    4    3    3    5
     3    4    2    3    4    4    3    2    3    4    3    3    3    3
     3    3    2    1    4    3    4    3    3    4    4    4    2    3
     4    3    2    4    3]]
[[   1 2104    3]
 [   1 1600    3]
 [   1 2400    3]
 [   1 1416    2]
 [   1 3000    4]
 [   1 1985    4]
 [   1 1534    3]
 [   1 1427    3]
 [   1 1380    3]
 [   1 1494    3]
 [   1 1940    4]
 [   1 2000    3]
 [   1 1890    3]
 [   1 4478    5]
 [   1 1268    

array([[89597.9095428 ],
       [  139.21067402],
       [-8738.01911233]])

In [4]:
print((np.array([1,1650,3])).dot(theta))


[293081.4643349]
